### ISSUE TITLE
pynamodb: ModuleNotFoundError: No module named 'typing_extensions'

### ISSUE THREAD

**Issue by shay314** [conda-forge/conda-forge.github.io#1266]
Issue:

<br/>
Environment (<code>conda list</code>):
<details>
When I try to import pynamodb I get:
ModuleNotFoundError: No module named 'typing_extensions'

Full traceback:
>>> from pynamodb.models import Model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/conda/envs/jobim/lib/python3.7/site-packages/pynamodb/models.py", line 29, in <module>
    from typing_extensions import Protocol
ModuleNotFoundError: No module named 'typing_extensions'

```
$ conda list
# packages in environment at /usr/local/conda/envs/jobim:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
aniso8601                 7.0.0                      py_0    defaults
apipkg                    1.5                      py37_0    defaults
asn1crypto                1.4.0                      py_0    defaults
astroid                   2.5              py37h06a4308_1    defaults
attrs                     20.3.0             pyhd3eb1b0_0    defaults
awscli                    1.19.16          py37h89c1867_0    defaults
base58                    2.1.0              pyhd8ed1ab_0    defaults
blinker                   1.4              py37h06a4308_0    defaults
boto3                     1.17.12            pyhd3eb1b0_0    defaults
botocore                  1.20.16            pyhd3eb1b0_1    defaults
brotlipy                  0.7.0           py37h27cfd23_1003    defaults
ca-certificates           2021.1.19            h06a4308_0    defaults
certifi                   2020.12.5        py37h06a4308_0    defaults
cffi                      1.14.0           py37h2e261b9_0    defaults
chardet                   4.0.0           py37h06a4308_1003    defaults
click                     7.1.2              pyhd3eb1b0_0    defaults
cloud-logging             0.0.9                    pypy_0    defaults
colorama                  0.4.3              pyhd3eb1b0_0    defaults
cryptography              2.3.1            py37hc365091_0    defaults
docutils                  0.15.2           py37h06a4308_1    defaults
elasticsearch             7.11.0             pyhd3eb1b0_0    defaults
execnet                   1.8.0              pyhd3eb1b0_0    defaults
flask                     1.1.2              pyhd3eb1b0_0    defaults
flask-graphql             2.0.1              pyh9f0ad1d_2    defaults
future                    0.18.2                   py37_1    defaults
google-pasta              0.2.0                      py_0    defaults
graphene                  2.1.8                      py_0    defaults
graphql-core              2.3.1                      py_0    defaults
graphql-relay             2.0.1                      py_0    defaults
graphql-server-core       1.2.0                      py_1    defaults
idna                      2.10               pyhd3eb1b0_0    defaults
importlib-metadata        2.0.0                      py_1    defaults
importlib_metadata        2.0.0                         1    defaults
iniconfig                 1.1.1              pyhd3eb1b0_0    defaults
isort                     5.7.0              pyhd3eb1b0_0    defaults
itsdangerous              1.1.0                    py37_0    defaults
jinja2                    2.11.3             pyhd3eb1b0_0    defaults
jmespath                  0.10.0                     py_0    defaults
lazy-object-proxy         1.5.2            py37h27cfd23_0    defaults
libblas                   3.8.0               17_openblas    defaults
libcblas                  3.8.0               17_openblas    defaults
libedit                   3.1.20191231         h14c3975_1    defaults
libffi                    3.2.1             hf484d3e_1007    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
liblapack                 3.8.0               17_openblas    defaults
libopenblas               0.3.10               h5a2b251_0    defaults
libprotobuf               3.6.0                hdbcaa40_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
lockfile                  0.12.2           py37h06a4308_0    defaults
lz4                       3.1.0            py37h27cfd23_0    defaults
lz4-c                     1.9.3                h2531618_0    defaults
markupsafe                1.1.1            py37h14c3975_1    defaults
mccabe                    0.6.1                    py37_1    defaults
mdblib                    1.0.18                     py_0    defaults
me-nebula                 0.1.497                    py_0    defaults
more-itertools            8.7.0              pyhd3eb1b0_0    defaults
pynamodb                  5.0.3              pyh44b312d_0    defaults
pyopenssl                 19.0.0                   py37_0    defaults
pyparsing                 2.4.7              pyhd3eb1b0_0    defaults
pysocks                   1.7.1                    py37_1    defaults
pytest                    6.2.2            py37h06a4308_2    defaults
pytest-forked             1.3.0              pyhd3eb1b0_0    defaults
pytest-xdist              2.2.1              pyhd3eb1b0_0    defaults
python                    3.7.0                h6e4f718_3    defaults
python-daemon             2.3.0            py37h06a4308_3    defaults
python-dateutil           2.8.1              pyhd3eb1b0_0    defaults
python-json-logger        2.0.1                      py_0    defaults
python_abi                3.7                     1_cp37m    defaults
pytz                      2021.1             pyhd3eb1b0_0    defaults
pyyaml                    5.4.1            py37h27cfd23_1    defaults
readline                  7.0                  h7b6447c_5    defaults
requests                  2.25.1             pyhd3eb1b0_0    defaults
rsa                       4.7.2              pyhd3eb1b0_1    defaults
run-mest                  0.0.4                      py_0    defaults
rx                        1.6.1                      py_0    defaults
s3transfer                0.3.4              pyhd3eb1b0_0    defaults
sagemaker-python-sdk      2.25.0           py37h89c1867_0    defaults
setuptools                52.0.0           py37h06a4308_0    defaults
six                       1.15.0           py37h06a4308_0    defaults
smdebug-rulesconfig       1.0.1              pyhd3deb0d_0    defaults
sqlalchemy                1.3.15           py37h7b6447c_1    defaults
sqlite                    3.33.0               h62c20be_0    defaults
tabulate                  0.8.9            py37h06a4308_0    defaults
tar                       1.32                 hd4ba37b_0    defaults
termcolor                 1.1.0            py37h06a4308_1    defaults
terraform                 0.12.29              h375a9b1_0    defaults
tk                        8.6.10               hbc83047_0    defaults
toml                      0.10.1                     py_0    defaults
tqdm                      4.56.0             pyhd3eb1b0_0    defaults
typed-ast                 1.4.2            py37h27cfd23_1    defaults
urllib3                   1.26.3             pyhd3eb1b0_0    defaults
werkzeug                  1.0.1              pyhd3eb1b0_0    defaults
wheel                     0.36.2             pyhd3eb1b0_0    defaults
wrapt                     1.12.1           py37h7b6447c_1    defaults
xz                        5.2.5                h7b6447c_0    defaults
yaml                      0.2.5                h7b6447c_0    defaults
zipp                      3.4.0              pyhd3eb1b0_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : jobim
    active env location : /usr/local/conda/envs/jobim
            shell level : 2
       user config file : /root/.condarc
 populated config files : /etc/conda/.condarc
          conda version : 4.9.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /usr/local/conda  (writable)
           channel URLs : https://artifactory.sddc.mobileye.com/artifactory/api/conda/me-conda-dev-local/linux-64
                          https://artifactory.sddc.mobileye.com/artifactory/api/conda/me-conda-dev-local/noarch
                          https://artifactory.sddc.mobileye.com/artifactory/api/conda/conda-anaconda-remote/linux-64
                          https://artifactory.sddc.mobileye.com/artifactory/api/conda/conda-anaconda-remote/noarch
                          https://artifactory.sddc.mobileye.com/artifactory/api/conda/conda-condaforge-remote/linux-64
                          https://artifactory.sddc.mobileye.com/artifactory/api/conda/conda-condaforge-remote/noarch
                          https://artifactory.sddc.mobileye.com/artifactory/api/conda/conda-bioconda-remote/linux-64
                          https://artifactory.sddc.mobileye.com/artifactory/api/conda/conda-bioconda-remote/noarch
          package cache : /usr/local/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /usr/local/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.22.0 CPython/3.7.6 Linux/4.9.0-0.bpo.6-amd64 ubuntu/18.04.4 glibc/2.27
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```
</details>

**Comment by beckermr** [comment]
Thank you for the note! Please make these issues on the feedstock.
