### ISSUE TITLE
Importing matplotlib.pyplot fails under Python 3.5.2 on Linux

### ISSUE THREAD

**Issue by Cadair** [conda-forge/conda-forge.github.io#190]
When creating a new matplotlib environment under Python 3.5.2 I get the following error unless I manually install `icu`

```
(sunpy-dev)stuart@dyn017220:~/GitHub/sunpy> cde  
discarding /home/stuart/.conda/envs/sunpy-dev/bin from PATH
stuart@dyn017220:~/GitHub/sunpy> conda create -n test python=3 matplotlib
Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment /home/stuart/.conda/envs/test:

The following NEW packages will be INSTALLED:

    cycler:          0.10.0-py35_0    
    fontconfig:      2.11.1-3         
    freetype:        2.6.3-1          
    libiconv:        1.14-2           
    libpng:          1.6.23-0         
    libxml2:         2.9.2-0          
    matplotlib:      1.5.2-np111py35_4
    mkl:             11.3.3-0         
    ncurses:         5.9-7            
    numpy:           1.11.1-py35_0    
    openssl:         1.0.2h-1         
    pip:             8.1.2-py35_0     
    pyparsing:       2.1.4-py35_0     
    pyqt:            4.11.4-py35_3    
    python:          3.5.2-1          
    python-dateutil: 2.5.3-py35_0     
    pytz:            2016.4-py35_0    
    qt:              4.8.7-3          
    readline:        6.2-2             (soft-link)
    setuptools:      23.0.0-py35_0    
    sip:             4.18-py35_0      
    six:             1.10.0-py35_0    
    sqlite:          3.13.0-1         
    tk:              8.5.19-0         
    wheel:           0.29.0-py35_0     (soft-link)
    xz:              5.2.2-0          
    zlib:            1.2.8-3          

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|#################################################################################################################################################################################################################| 100%
#
# To activate this environment, use:
# $ source activate test
#
# To deactivate this environment, use:
# $ source deactivate
#
stuart@dyn017220:~/GitHub/sunpy> cac test
discarding /opt/miniconda/bin from PATH
prepending /home/stuart/.conda/envs/test/bin to PATH
(test)stuart@dyn017220:~/GitHub/sunpy> python
Python 3.5.2 | packaged by conda-forge | (default, Jul  7 2016, 12:51:46) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
Traceback (most recent call last):
  File "/etc/pythonstart", line 7, in <module>
    import readline
ImportError: /home/stuart/.conda/envs/test/lib/python3.5/lib-dynload/../../libreadline.so.6: undefined symbol: PC
>>> import matplotlib.pyplot as plt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stuart/.conda/envs/test/lib/python3.5/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/stuart/.conda/envs/test/lib/python3.5/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/home/stuart/.conda/envs/test/lib/python3.5/site-packages/matplotlib/backends/backend_qt4agg.py", line 18, in <module>
    from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase
  File "/home/stuart/.conda/envs/test/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import QtCore
  File "/home/stuart/.conda/envs/test/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 31, in <module>
    from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__
  File "/home/stuart/.conda/envs/test/lib/python3.5/site-packages/matplotlib/backends/qt_compat.py", line 137, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: libicui18n.so.56: cannot open shared object file: No such file or directory
>>> 
```

**Comment by ocefpaf** [comment]
This is reported in https://github.com/conda-forge/matplotlib-feedstock/issues/36. Closing to avoid the duplication.  Thanks @Cadair!
