### ISSUE TITLE
Miniconda - Channel conda-forge not working - Traceback message

### ISSUE THREAD

**Issue by herry23xet** [conda-forge/conda-forge.github.io#1966]
### Conda-forge documentation

- [X] I could not solve my problem using the conda-forge documentation.

### Installed packages

```shell
Default Miniconda Conda 23.3.1 Python 3.10.10 released April 24, 2023
```

### Environment info

```shell
Not Working with the Problem.
```

### Issue

I have installed Miniconda on my Windows 10 PC. I have followed the Data Science book by Wes McKinney. I did everything 1:1 like this. I have then added conda-forge as a channel and also provided it with "strict".

```
(base) $ conda config --add channels conda-forge
(base) $ conda config --set channel_priority strict
```

I then executed `conda update conda` in the base environment and installed everything. Then when I typed `conda list`, I got a weird message with "traceback" in "Anaconda Promt". Also other commands like `conda --version` did not work without such a message. I searched for solutions but only found old amounts where either Conda was old or it was a bug from Conda. The only solution that worked for me was to reinstall Miniconda. However, whenever I added conda-forge and did an update, it broke.

I also tried running `conda update --all`. Without success. I also updated everything via the default channel first and then added conda-forge. Did not work either. I also tried different sequences of this process. Without success.

Otherwise I haven't changed anything and this error only ever occurs when I add conda-forge as a channel. The version I installed is the current one:
_Latest - Conda 23.3.1 Python 3.10.10 released April 24, 2023_
But as you know, I also updated it via Conda when I tried it. But there also came out this message.

Here's what I get out of it:

```
(base) C:\Users\Name>conda list
Traceback (most recent call last):
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\exception_handler.py", line 16, in __call__
    return func(*args, **kwargs)
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\cli\main.py", line 70, in main_subshell
    p = generate_parser()
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 65, in generate_parser
    p = ArgumentParser(
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 152, in __init__
    self._subcommands = context.plugin_manager.get_hook_results("subcommands")
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\base\context.py", line 502, in plugin_manager
    from ..plugins.manager import get_plugin_manager
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\plugins\__init__.py", line 3, in <module>
    from .hookspec import hookimpl  # noqa: F401
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\plugins\hookspec.py", line 9, in <module>
    from .types import CondaSolver, CondaSubcommand, CondaVirtualPackage
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\plugins\types.py", line 7, in <module>
    from ..core.solve import Solver
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\core\solve.py", line 41, in <module>
    from .index import _supplement_index_with_system, get_reduced_index
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\core\index.py", line 22, in <module>
    from .package_cache_data import PackageCacheData
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\core\package_cache_data.py", line 56, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\core\path_actions.py", line 35, in <module>
    from ..gateways.connection.download import download
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\gateways\connection\__init__.py", line 4, in <module>
    from requests import ConnectionError, HTTPError, Session
  File "C:\Users\Name\miniconda3\lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Users\Name\miniconda3\lib\site-packages\urllib3\__init__.py", line 17, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "C:\Users\Name\miniconda3\lib\site-packages\urllib3\connectionpool.py", line 14, in <module>
    from ._request_methods import RequestMethods
  File "C:\Users\Name\miniconda3\lib\site-packages\urllib3\_request_methods.py", line 10, in <module>
    from .response import BaseHTTPResponse
  File "C:\Users\Name\miniconda3\lib\site-packages\urllib3\response.py", line 277, in <module>
    class BaseHTTPResponse(io.IOBase):
  File "C:\Users\Name\miniconda3\lib\site-packages\urllib3\response.py", line 287, in BaseHTTPResponse
    DECODER_ERROR_CLASSES += (brotli.error,)
AttributeError: module 'brotli' has no attribute 'error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Name\miniconda3\Scripts\conda-script.py", line 12, in <module>
    sys.exit(main())
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\cli\main.py", line 129, in main
    return conda_exception_handler(main, *args, **kwargs)
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\exception_handler.py", line 376, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\exception_handler.py", line 19, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\exception_handler.py", line 75, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\exception_handler.py", line 88, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\exception_handler.py", line 159, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\cli\main_info.py", line 15, in <module>
    from ..core.index import _supplement_index_with_system
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\core\index.py", line 22, in <module>
    from .package_cache_data import PackageCacheData
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\core\package_cache_data.py", line 56, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\core\path_actions.py", line 35, in <module>
    from ..gateways.connection.download import download
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\gateways\connection\__init__.py", line 4, in <module>
    from requests import ConnectionError, HTTPError, Session
  File "C:\Users\Name\miniconda3\lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Users\Name\miniconda3\lib\site-packages\urllib3\__init__.py", line 17, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "C:\Users\Name\miniconda3\lib\site-packages\urllib3\connectionpool.py", line 14, in <module>
    from ._request_methods import RequestMethods
  File "C:\Users\Name\miniconda3\lib\site-packages\urllib3\_request_methods.py", line 10, in <module>
    from .response import BaseHTTPResponse
  File "C:\Users\Name\miniconda3\lib\site-packages\urllib3\response.py", line 277, in <module>
    class BaseHTTPResponse(io.IOBase):
  File "C:\Users\Name\miniconda3\lib\site-packages\urllib3\response.py", line 287, in BaseHTTPResponse
    DECODER_ERROR_CLASSES += (brotli.error,)
AttributeError: module 'brotli' has no attribute 'error'

(base) C:\Users\Name>conda list
Traceback (most recent call last):
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\exception_handler.py", line 16, in __call__
    return func(*args, **kwargs)
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\cli\main.py", line 70, in main_subshell
    p = generate_parser()
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 65, in generate_parser
    p = ArgumentParser(
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 152, in __init__
    self._subcommands = context.plugin_manager.get_hook_results("subcommands")
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\base\context.py", line 502, in plugin_manager
    from ..plugins.manager import get_plugin_manager
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\plugins\__init__.py", line 3, in <module>
    from .hookspec import hookimpl  # noqa: F401
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\plugins\hookspec.py", line 9, in <module>
    from .types import CondaSolver, CondaSubcommand, CondaVirtualPackage
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\plugins\types.py", line 7, in <module>
    from ..core.solve import Solver
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\core\solve.py", line 41, in <module>
    from .index import _supplement_index_with_system, get_reduced_index
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\core\index.py", line 22, in <module>
    from .package_cache_data import PackageCacheData
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\core\package_cache_data.py", line 56, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\core\path_actions.py", line 35, in <module>
    from ..gateways.connection.download import download
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\gateways\connection\__init__.py", line 4, in <module>
    from requests import ConnectionError, HTTPError, Session
  File "C:\Users\Name\miniconda3\lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Users\Name\miniconda3\lib\site-packages\urllib3\__init__.py", line 17, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "C:\Users\Name\miniconda3\lib\site-packages\urllib3\connectionpool.py", line 14, in <module>
    from ._request_methods import RequestMethods
  File "C:\Users\Name\miniconda3\lib\site-packages\urllib3\_request_methods.py", line 10, in <module>
    from .response import BaseHTTPResponse
  File "C:\Users\Name\miniconda3\lib\site-packages\urllib3\response.py", line 277, in <module>
    class BaseHTTPResponse(io.IOBase):
  File "C:\Users\Name\miniconda3\lib\site-packages\urllib3\response.py", line 287, in BaseHTTPResponse
    DECODER_ERROR_CLASSES += (brotli.error,)
AttributeError: module 'brotli' has no attribute 'error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Name\miniconda3\Scripts\conda-script.py", line 12, in <module>
    sys.exit(main())
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\cli\main.py", line 129, in main
    return conda_exception_handler(main, *args, **kwargs)
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\exception_handler.py", line 376, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\exception_handler.py", line 19, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\exception_handler.py", line 75, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\exception_handler.py", line 88, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\exception_handler.py", line 159, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\cli\main_info.py", line 15, in <module>
    from ..core.index import _supplement_index_with_system
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\core\index.py", line 22, in <module>
    from .package_cache_data import PackageCacheData
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\core\package_cache_data.py", line 56, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\core\path_actions.py", line 35, in <module>
    from ..gateways.connection.download import download
  File "C:\Users\Name\miniconda3\lib\site-packages\conda\gateways\connection\__init__.py", line 4, in <module>
    from requests import ConnectionError, HTTPError, Session
  File "C:\Users\Name\miniconda3\lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Users\Name\miniconda3\lib\site-packages\urllib3\__init__.py", line 17, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "C:\Users\Name\miniconda3\lib\site-packages\urllib3\connectionpool.py", line 14, in <module>
    from ._request_methods import RequestMethods
  File "C:\Users\Name\miniconda3\lib\site-packages\urllib3\_request_methods.py", line 10, in <module>
    from .response import BaseHTTPResponse
  File "C:\Users\Name\miniconda3\lib\site-packages\urllib3\response.py", line 277, in <module>
    class BaseHTTPResponse(io.IOBase):
  File "C:\Users\Name\miniconda3\lib\site-packages\urllib3\response.py", line 287, in BaseHTTPResponse
    DECODER_ERROR_CLASSES += (brotli.error,)
AttributeError: module 'brotli' has no attribute 'error'

(base) C:\Users\Name>
```

**Comment by jaimergp** [comment]
This sounds like an incompatibility in `conda` and `brotlipy`, nothing to do with conda-forge itself. See https://github.com/conda/conda/issues/9903 for possible workarounds, and thanks for the report!
