### ISSUE TITLE
Python3.10 pip breaks

### ISSUE THREAD

**Issue by MarcoMontevechiFilho1** [conda-forge/conda-forge.github.io#2008]
### Conda-forge documentation

- [X] I could not solve my problem using the conda-forge documentation.

### Installed packages

```shell
List of packages in environment: "/home/marco/micromamba/envs/teste3"

  Name              Version    Build               Channel    
────────────────────────────────────────────────────────────────
  _libgcc_mutex     0.1        conda_forge         conda-forge
  _openmp_mutex     4.5        2_gnu               conda-forge
  bzip2             1.0.8      h7f98852_4          conda-forge
  ca-certificates   2023.7.22  hbcca054_0          conda-forge
  ld_impl_linux-64  2.40       h41732ed_0          conda-forge
  libffi            3.4.2      h7f98852_5          conda-forge
  libgcc-ng         13.2.0     h807b86a_0          conda-forge
  libgomp           13.2.0     h807b86a_0          conda-forge
  libnsl            2.0.0      h7f98852_0          conda-forge
  libsqlite         3.43.0     h2797004_0          conda-forge
  libuuid           2.38.1     h0b41bf4_0          conda-forge
  libzlib           1.2.13     hd590300_5          conda-forge
  ncurses           6.4        hcb278e6_0          conda-forge
  openssl           3.1.2      hd590300_0          conda-forge
  pip               23.2.1     pyhd8ed1ab_0        conda-forge
  python            3.10.12    hd12c33a_0_cpython  conda-forge
  readline          8.2        h8228510_1          conda-forge
  setuptools        68.2.2     pyhd8ed1ab_0        conda-forge
  tk                8.6.12     h27826a3_0          conda-forge
  tzdata            2023c      h71feb2d_0          conda-forge
  wheel             0.41.2     pyhd8ed1ab_0        conda-forge
  xz                5.2.6      h166bdaf_0          conda-forge
```

### Environment info

```shell
libmamba version : 1.4.9
     micromamba version : 1.4.9
           curl version : libcurl/7.88.1 OpenSSL/3.1.1 zlib/1.2.13 zstd/1.5.2 libssh2/1.11.0 nghttp2/1.52.0
     libarchive version : libarchive 3.6.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.2
       envs directories : /home/marco/micromamba/envs
          package cache : /home/marco/micromamba/pkgs
                          /home/marco/.mamba/pkgs
            environment : teste3 (active)
           env location : /home/marco/micromamba/envs/teste3
      user config files : /home/marco/.mambarc
 populated config files : 
       virtual packages : __unix=0=0
                          __linux=6.2.0=0
                          __glibc=2.35=0
                          __archspec=1=x86_64
               channels : 
       base environment : /home/marco/micromamba
               platform : linux-64
```

### Issue

I apologize if this is not the place to report the issue. Please redirect me to the correct place if im misplaced here.

I reproduced the error both with conda 23.7.2 and micromamba 1.4.9 

In ubuntu 22.04, i downloaded micromamba binary from https://micro.mamba.pm/api/micromamba/linux-64/latest and conda from https://www.anaconda.com/download/
I have a minimalist setup.py example which im using to test pip. I attach the file in this message.

When i do:
```
micromamba create -n test
micromamba activate test
micromamba install -c conda-forge python=3.9 pip
pip install . #Using the setup.py file
```

Everything works fine. However, if i switch python=3.9 to python=3.10 i get:
```

Processing /tmp/teste
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/teste/setup.py", line 3, in <module>
          setup(name='Distutils',
        File "/home/marco/micromamba/envs/teste3/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/home/marco/micromamba/envs/teste3/lib/python3.10/site-packages/setuptools/dist.py", line 303, in __init__
          _Distribution.__init__(self, dist_attrs)
        File "/home/marco/micromamba/envs/teste3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
          self.finalize_options()
        File "/home/marco/micromamba/envs/teste3/lib/python3.10/site-packages/setuptools/dist.py", line 679, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File "/home/marco/micromamba/envs/teste3/lib/python3.10/site-packages/setuptools/dist.py", line 678, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File "/home/marco/micromamba/envs/teste3/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
          module = import_module(match.group('module'))
        File "/home/marco/micromamba/envs/teste3/lib/python3.10/importlib/__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
        File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 883, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "/home/marco/.local/lib/python3.10/site-packages/setuptools_scm/__init__.py", line 13, in <module>
          from ._entrypoints import _call_entrypoint_fn
        File "/home/marco/.local/lib/python3.10/site-packages/setuptools_scm/_entrypoints.py", line 11, in <module>
          from .version import ScmVersion
        File "/home/marco/.local/lib/python3.10/site-packages/setuptools_scm/version.py", line 24, in <module>
          from ._version_cls import Version as PkgVersion
        File "/home/marco/.local/lib/python3.10/site-packages/setuptools_scm/_version_cls.py", line 5, in <module>
          from packaging.version import InvalidVersion
      ModuleNotFoundError: No module named 'packaging'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
Everything is reproducible with conda.

By testing it in a fresh ubuntu 22.04 container without conda environments, it worked out-of-the-box without me having to install packaging module, so i suppose there is something wrong with python3.10+pip packaging in conda.

 Thanks in advance for any answers. 

[setup_py.gz](https://github.com/conda-forge/conda-forge.github.io/files/12602223/setup_py.gz)

**Comment by isuruf** [comment]
You have a `.local` directory in your home directory that interfere.

**Comment by MarcoMontevechiFilho1** [comment]
@isuruf oops, didnt notice that. Indeed, after testing in a fresh ubuntu 22.04 container it worked nicely.
I had tested if python3.10 worked without an environment but didnt think about testing if the virtual environment worked in the container.

Closing the issue, thanks for the hint!

**Comment by MarcoMontevechiFilho1** [comment]
@isuruf oops, didnt notice that. Indeed, after testing in a fresh ubuntu 22.04 container it worked nicely.
I had tested if python3.10 worked without an environment but didnt think about testing if the virtual environment worked in the container.

Closing the issue, thanks for the hint!
