### ISSUE TITLE
Error linking conda-libmamba-solver

### ISSUE THREAD

**Issue by peastman** [conda-forge/conda-forge.github.io#2048]
### Conda-forge documentation

- [X] I could not solve my problem using the conda-forge documentation.

### Installed packages

```shell
# packages in environment at C:\Miniforge:
#
# Name                    Version                   Build  Channel
anaconda-client           1.12.1             pyhd8ed1ab_1    conda-forge
vc14_runtime              14.36.32532         hfdfe4a8_17    conda-forge
vs2015_runtime            14.36.32532         h05e6639_17    conda-forge
watchgod                  0.8.2              pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.12             pyhd8ed1ab_0    conda-forge
wheel                     0.41.2             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
yaml-cpp                  0.8.0                h63175ca_0    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zstandard                 0.19.0          py310h8d17308_0    conda-forge
zstd                      1.5.5                h12be248_0    conda-forge
```

### Environment info

```shell
n/a
```

### Issue

I'm trying to build packages at https://github.com/conda-forge/openmm-feedstock/pull/123.  All the Windows builds fail with this exception.

```
Error while loading conda entry point: conda-libmamba-solver (DLL load failed while importing bindings: The specified procedure could not be found.)
Traceback (most recent call last):
  File "C:\Miniforge\Scripts\conda-mambabuild-script.py", line 5, in <module>
    from boa.cli.mambabuild import main
  File "C:\Miniforge\lib\site-packages\boa\cli\mambabuild.py", line 21, in <module>
    from boa.core.solver import MambaSolver
  File "C:\Miniforge\lib\site-packages\boa\core\solver.py", line 22, in <module>
    import libmambapy
  File "C:\Miniforge\lib\site-packages\libmambapy\__init__.py", line 7, in <module>
    raise e
  File "C:\Miniforge\lib\site-packages\libmambapy\__init__.py", line 4, in <module>
    from libmambapy.bindings import *  # noqa: F401,F403
ImportError: DLL load failed while importing bindings: The specified procedure could not be found.
```

**Comment by jakirkham** [comment]
cc @jaimergp

**Comment by jaimergp** [comment]
Is this https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/628? Should have been fixed now. Let me know if a retry doesn't fix it.

**Comment by jaimergp** [comment]
Ah yea, it did. Closing here then. Thanks for reporting!

**Comment by jakirkham** [comment]
Yep thanks Jaime! 🙏
