### ISSUE TITLE
MAPIE release 0.9.0

### ISSUE THREAD

**Issue by LacombeLouis** [conda-forge/conda-forge.github.io#2288]
### Your question:

Hey, I’m one of the developers of the [MAPIE](https://github.com/scikit-learn-contrib/MAPIE) library. We made a release on September 3rd: [link](https://github.com/scikit-learn-contrib/MAPIE/releases/tag/v0.9.0). Until now, we haven’t had any issues with the previous [conda-forge releases](https://github.com/conda-forge/mapie-feedstock).

Any pointers to help me understand why version 0.9.0 didn’t go through? Thanks in advance!

**Comment by dopplershift** [comment]
If you check the "Errored Version Updates" section on the [conda-forge status page](https://conda-forge.org/status/) you can see:
```
1.00 attempts - bot error ([bot CI job](https://github.com/regro/cf-scripts/actions/runs/10693273273)): main:
Traceback (most recent call last):
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1060, in _validate_conn
    conn.connect()
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (, 'Connection to api.github.com timed out. (connect timeout=4)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/urllib3/connectionpool.py", line 801, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/urllib3/util/retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /user (Caused by ConnectTimeoutError(, 'Connection to api.github.com timed out. (connect timeout=4)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/github3/models.py", line 201, in _request
    return request_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/github3/session.py", line 171, in request
    response = super().request(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/requests/adapters.py", line 688, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /user (Caused by ConnectTimeoutError(, 'Connection to api.github.com timed out. (connect timeout=4)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 638, in _run_migrator_on_feedstock_branch
    migrator_uid, pr_json = run_with_tmpdir(
                            ^^^^^^^^^^^^^^^^
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 211, in run_with_tmpdir
    return run(
           ^^^^
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 494, in run
    pr_json = push_repo(
              ^^^^^^^^^^
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py", line 1019, in push_repo
    gh_username = github3_client().me().login
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/github3/decorators.py", line 24, in auth_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/github3/github.py", line 1590, in me
    json = self._json(self._get(url), 200)
                      ^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/github3/models.py", line 216, in _get
    return self._request("get", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/github3/models.py", line 206, in _request
    raise exceptions.ConnectionError(exc)
github3.exceptions.ConnectionError: : A connection-level exception occurred: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /user (Caused by ConnectTimeoutError(, 'Connection to api.github.com timed out. (connect timeout=4)'))
```

So I think it was just a network glitch that the bot *should* get around to retrying (I think). You could try [manually requesting the bot do the update](https://conda-forge.org/docs/maintainer/infrastructure/#conda-forge-admin-please-update-version), or just make the PR yourself.
