### ISSUE TITLE
All Travis Builds on this Repo Have been Failing

### ISSUE THREAD

**Issue by scopatz** [conda-forge/conda-forge.github.io#287]
If you look at the build history, everything in this repo has been failing for about 3 weeks now: https://travis-ci.org/conda-forge/conda-forge.github.io/builds The following representative error makes it seem like this is coming from conda-execute. 

```
Traceback (most recent call last):
  File "/home/travis/conda/bin/conda-execute", line 11, in <module>
    load_entry_point('conda-execute==0.7.0', 'console_scripts', 'conda-execute')()
  File "/home/travis/conda/lib/python3.5/site-packages/conda_execute/execute.py", line 197, in main
    exit(execute(path, force_env=args.force_env, arguments=args.remaining_args))
  File "/home/travis/conda/lib/python3.5/site-packages/conda_execute/execute.py", line 89, in execute
    env_prefix = create_env(env_spec, force_env, spec.get('channels', []))
  File "/home/travis/conda/lib/python3.5/site-packages/conda_execute/tmpenv.py", line 61, in create_env
    with Locked(env_locn):
  File "/home/travis/conda/lib/python3.5/site-packages/conda_execute/lock.py", line 16, in __init__
    return conda.lock.Locked.__init__(self, path)
  File "/home/travis/conda/lib/python3.5/site-packages/conda/lock.py", line 119, in __init__
    assert isdir(dirname(self.directory_path)), "{0} doesn't exist".format(self.directory_path)
AssertionError: /home/travis/conda/tmp_envs/.conda-lock_52da98d4f35605981299 doesn't exist
```

I am not sure how to fix this...

**Comment by jakirkham** [comment]
Fixed by PR ( https://github.com/pelson/conda-execute/pull/36 ) to `conda-execute`.
