### ISSUE TITLE
Issue with PyQt5 when using conda-forge

### ISSUE THREAD

**Issue by astrofrog** [conda-forge/conda-forge.github.io#331]
I am having issues in environments where I install PyQt5 from defaults and also some packages from conda-forge. The following example illustrates this:

```
(debug-travis-6) tom@air:~/Code/glue$ conda create -n debug-travis-8 -c conda-forge pyqt=5 qtpy scandir python=2.7 matplotlib nomkl
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /home/tom/miniconda3/envs/debug-travis-8:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    gst-plugins-base-1.8.0     |                0         4.0 MB  conda-forge
    numpy-1.11.3               |     py27_nomkl_0         6.3 MB
    qtpy-1.2.1                 |           py27_0          26 KB  conda-forge
    subprocess32-3.2.7         |           py27_0          55 KB  conda-forge
    wheel-0.29.0               |           py27_0          81 KB  conda-forge
    matplotlib-2.0.0           |      np111py27_0        11.1 MB
    ------------------------------------------------------------
                                           Total:        21.6 MB

The following NEW packages will be INSTALLED:

    ca-certificates:  2016.9.26-0         conda-forge
    cairo:            1.14.8-0                       
    certifi:          2017.1.23-py27_0    conda-forge
    cycler:           0.10.0-py27_0       conda-forge
    dbus:             1.10.10-1           conda-forge
    expat:            2.1.0-2             conda-forge
    fontconfig:       2.12.1-3                       
    freetype:         2.5.5-2                        
    functools32:      3.2.3.2-py27_1      conda-forge
    gettext:          0.19.7-1            conda-forge
    glib:             2.51.0-2            conda-forge
    gst-plugins-base: 1.8.0-0             conda-forge
    gstreamer:        1.8.0-1             conda-forge
    icu:              54.1-0                         
    jpeg:             9b-0                conda-forge
    libffi:           3.2.1-3             conda-forge
    libgcc:           5.2.0-0                        
    libgfortran:      3.0.0-1                        
    libiconv:         1.14-4              conda-forge
    libpng:           1.6.28-0            conda-forge
    libxcb:           1.12-0              conda-forge
    libxml2:          2.9.3-6             conda-forge
    matplotlib:       2.0.0-np111py27_0              
    ncurses:          5.9-10              conda-forge
    nomkl:            1.0-0                          
    numpy:            1.11.3-py27_nomkl_0             [nomkl]
    openblas:         0.2.19-0            conda-forge
    openssl:          1.0.2h-3            conda-forge
    pcre:             8.39-0              conda-forge
    pip:              9.0.1-py27_0        conda-forge
    pixman:           0.34.0-0            conda-forge
    pycairo:          1.10.0-py27_0                  
    pyparsing:        2.1.10-py27_0       conda-forge
    pyqt:             5.6.0-py27_2                   
    python:           2.7.12-1            conda-forge
    python-dateutil:  2.6.0-py27_0        conda-forge
    pytz:             2016.10-py27_0      conda-forge
    qt:               5.6.2-3                        
    qtpy:             1.2.1-py27_0        conda-forge
    readline:         6.2-0               conda-forge
    scandir:          1.3-py27_1          conda-forge
    setuptools:       33.1.0-py27_0       conda-forge
    sip:              4.18-py27_1         conda-forge
    six:              1.10.0-py27_1       conda-forge
    sqlite:           3.13.0-1            conda-forge
    subprocess32:     3.2.7-py27_0        conda-forge
    tk:               8.5.19-1            conda-forge
    wheel:            0.29.0-py27_0       conda-forge
    xz:               5.0.5-1             conda-forge
    zlib:             1.2.11-0            conda-forge

Proceed ([y]/n)? y

Fetching packages ...
gst-plugins-ba 100% |#######################################################################################################| Time: 0:00:01   3.62 MB/s
numpy-1.11.3-p 100% |#######################################################################################################| Time: 0:00:00   7.05 MB/s
qtpy-1.2.1-py2 100% |#######################################################################################################| Time: 0:00:00 248.44 kB/s
subprocess32-3 100% |#######################################################################################################| Time: 0:00:00 277.54 kB/s
wheel-0.29.0-p 100% |#######################################################################################################| Time: 0:00:00 282.53 kB/s
matplotlib-2.0 100% |#######################################################################################################| Time: 0:00:01   7.86 MB/s
Extracting packages ...
[      COMPLETE      ]|##########################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|##########################################################################################################################| 100%
#
# To activate this environment, use:
# > source activate debug-travis-8
#
# To deactivate this environment, use:
# > source deactivate debug-travis-8
#
(debug-travis-6) tom@air:~/Code/glue$ source activate debug-travis-8
(debug-travis-8) tom@air:~/Code/glue$ python -c 'from qtpy import PYQT5; import scandir'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tom/miniconda3/envs/debug-travis-8/lib/python2.7/site-packages/scandir.py", line 435, in <module>
    libc = ctypes.CDLL(ctypes.util.find_library('c'), use_errno=True)
  File "/home/tom/miniconda3/envs/debug-travis-8/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/tom/miniconda3/envs/debug-travis-8/lib/python2.7/site-packages/PyQt5/../../.././libgobject-2.0.so.0: undefined symbol: g_date_time_unref
```

Note that PyQt5 is of course from defaults, but the issue only happens if I add the ``-c conda-forge`` to the environment creation, which suggests to me there is some kind of incompatibility, but I'm not sure where. Does anyone have any ideas?

Example without ``-c conda-forge``:

```
(debug-travis-8) tom@air:~/Code/glue$ conda create -n debug-travis-9 pyqt=5 qtpy scandir python=2.7 matplotlib nomkl
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /home/tom/miniconda3/envs/debug-travis-9:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    jpeg-9b                    |                0         941 KB
    pixman-0.34.0              |                0         3.8 MB
    openblas-0.2.19            |                0         3.0 MB
    functools32-3.2.3.2        |           py27_0          15 KB
    pyparsing-2.1.4            |           py27_0          70 KB
    pytz-2016.10               |           py27_0         205 KB
    qtpy-1.2.1                 |           py27_0          28 KB
    six-1.10.0                 |           py27_0          16 KB
    subprocess32-3.2.7         |           py27_0          55 KB
    wheel-0.29.0               |           py27_0          81 KB
    cycler-0.10.0              |           py27_0          11 KB
    python-dateutil-2.6.0      |           py27_0         232 KB
    gst-plugins-base-1.8.0     |                0         3.1 MB
    ------------------------------------------------------------
                                           Total:        11.6 MB

The following NEW packages will be INSTALLED:

    cairo:            1.14.8-0           
    cycler:           0.10.0-py27_0      
    dbus:             1.10.10-0          
    expat:            2.1.0-0            
    fontconfig:       2.12.1-3           
    freetype:         2.5.5-2            
    functools32:      3.2.3.2-py27_0     
    glib:             2.50.2-1           
    gst-plugins-base: 1.8.0-0            
    gstreamer:        1.8.0-0            
    icu:              54.1-0             
    jpeg:             9b-0               
    libffi:           3.2.1-1            
    libgcc:           5.2.0-0            
    libgfortran:      3.0.0-1            
    libiconv:         1.14-0             
    libpng:           1.6.27-0           
    libxcb:           1.12-1             
    libxml2:          2.9.4-0            
    matplotlib:       2.0.0-np111py27_0  
    nomkl:            1.0-0              
    numpy:            1.11.3-py27_nomkl_0 [nomkl]
    openblas:         0.2.19-0           
    openssl:          1.0.2k-0           
    pcre:             8.39-1             
    pip:              9.0.1-py27_1       
    pixman:           0.34.0-0           
    pycairo:          1.10.0-py27_0      
    pyparsing:        2.1.4-py27_0       
    pyqt:             5.6.0-py27_2       
    python:           2.7.13-0           
    python-dateutil:  2.6.0-py27_0       
    pytz:             2016.10-py27_0     
    qt:               5.6.2-3            
    qtpy:             1.2.1-py27_0       
    readline:         6.2-2              
    scandir:          1.4-py27_0         
    setuptools:       27.2.0-py27_0      
    sip:              4.18-py27_0        
    six:              1.10.0-py27_0      
    sqlite:           3.13.0-0           
    subprocess32:     3.2.7-py27_0       
    tk:               8.5.18-0           
    wheel:            0.29.0-py27_0      
    zlib:             1.2.8-3            

Proceed ([y]/n)? y

Pruning fetched packages from the cache ...
Fetching packages ...
jpeg-9b-0.tar. 100% |#######################################################################################################| Time: 0:00:00   5.71 MB/s
pixman-0.34.0- 100% |#######################################################################################################| Time: 0:00:00   6.18 MB/s
openblas-0.2.1 100% |#######################################################################################################| Time: 0:00:00   5.88 MB/s
functools32-3. 100% |#######################################################################################################| Time: 0:00:00   1.41 MB/s
pyparsing-2.1. 100% |#######################################################################################################| Time: 0:00:00   2.35 MB/s
pytz-2016.10-p 100% |#######################################################################################################| Time: 0:00:00   3.12 MB/s
qtpy-1.2.1-py2 100% |#######################################################################################################| Time: 0:00:00   2.09 MB/s
six-1.10.0-py2 100% |#######################################################################################################| Time: 0:00:00   1.82 MB/s
subprocess32-3 100% |#######################################################################################################| Time: 0:00:00   2.60 MB/s
wheel-0.29.0-p 100% |#######################################################################################################| Time: 0:00:00   3.11 MB/s
cycler-0.10.0- 100% |#######################################################################################################| Time: 0:00:00   7.67 MB/s
python-dateuti 100% |#######################################################################################################| Time: 0:00:00   4.42 MB/s
gst-plugins-ba 100% |#######################################################################################################| Time: 0:00:00   4.22 MB/s
Extracting packages ...
[      COMPLETE      ]|##########################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|##########################################################################################################################| 100%
#
# To activate this environment, use:
# > source activate debug-travis-9
#
# To deactivate this environment, use:
# > source deactivate debug-travis-9
#

(debug-travis-8) tom@air:~/Code/glue$ source activate debug-travis-9
(debug-travis-9) tom@air:~/Code/glue$ python -c 'from qtpy import PYQT5; import scandir'
(debug-travis-9) tom@air:~/Code/glue$ 
```

**Comment by hmaarrfk** [comment]
I'm going to this as "stale" or "won't fix". Ultimately, conda-forge and main have diverged. I think that qt packaging has greatly improved and that future issues should be discussed at 
https://github.com/conda-forge/qt-main-feedstock/
