### ISSUE TITLE
Periodic failiure

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-forge.github.io#52]
https://travis-ci.org/conda-forge/conda-forge.github.io/jobs/117396831

```
Arguments passed: Namespace(code=None, force_env=False, path='./scripts/update_teams.py', quiet=False, remaining_args=['./feedstocks_repo/feedstocks'], verbose=True)
Traceback (most recent call last):
  File "/home/travis/conda/bin/conda-execute", line 9, in <module>
    load_entry_point('conda-execute==0.4.1', 'console_scripts', 'conda-execute')()
  File "/home/travis/conda/lib/python3.5/site-packages/conda_execute/execute.py", line 177, in main
    exit(execute(path, force_env=args.force_env, arguments=args.remaining_args))
  File "/home/travis/conda/lib/python3.5/site-packages/conda_execute/execute.py", line 75, in execute
    with open(path, 'r') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/build/conda-forge/conda-forge.github.io/feedstocks_repo/scripts/update_teams.py'
```

If anybody else sees this, please ping the build job in the issue. Some more evidence will be useful in diagnosing this one I think.

**Comment by ocefpaf** [comment]
I am getting this today (but I don't think it is related.)

```
Prefix: /home/travis/conda/tmp_envs/c08cdac88042ff143569
Running command: ['python', '/home/travis/build/conda-forge/conda-forge.github.io/scripts/update_feedstocks_submodules.py', './feedstocks_repo']
Adding auditwheel to submodules.
Traceback (most recent call last):
  File "/home/travis/build/conda-forge/conda-forge.github.io/scripts/update_feedstocks_submodules.py", line 44, in <module>
    url=feedstock.clone_url)
  File "/home/travis/conda/tmp_envs/c08cdac88042ff143569/lib/python3.5/site-packages/git/repo/base.py", line 300, in create_submodule
    return Submodule.add(self, *args, **kwargs)
  File "/home/travis/conda/tmp_envs/c08cdac88042ff143569/lib/python3.5/site-packages/git/objects/submodule/base.py", line 415, in add
    sm.binsha = mrepo.head.commit.binsha
  File "/home/travis/conda/tmp_envs/c08cdac88042ff143569/lib/python3.5/site-packages/git/refs/symbolic.py", line 183, in _get_commit
    obj = self._get_object()
  File "/home/travis/conda/tmp_envs/c08cdac88042ff143569/lib/python3.5/site-packages/git/refs/symbolic.py", line 176, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
  File "/home/travis/conda/tmp_envs/c08cdac88042ff143569/lib/python3.5/site-packages/git/refs/symbolic.py", line 125, in dereference_recursive
    hexsha, ref_path = cls._get_ref_info(repo, ref_path)
  File "/home/travis/conda/tmp_envs/c08cdac88042ff143569/lib/python3.5/site-packages/git/refs/symbolic.py", line 157, in _get_ref_info
    raise ValueError("Reference at %r does not exist" % ref_path)
ValueError: Reference at 'refs/heads/master' does not exist
CalledProcessError: Command '['python', '/home/travis/build/conda-forge/conda-forge.github.io/scripts/update_feedstocks_submodules.py', './feedstocks_repo']' returned non-zero exit status 1
```

**Comment by pelson** [comment]
Thanks @ocefpaf. See #54
