### ISSUE TITLE
Error updating feedstock repos

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#54]
See an example in this [log]( https://travis-ci.org/conda-forge/conda-forge.github.io/jobs/117854773#L241 ).

**Comment by pelson** [comment]
Relates to the empty repos in https://github.com/conda-forge/auditwheel-feedstock.

It would be healthy to be less brittle to empty repos though :+1:

**Comment by jakirkham** [comment]
Yikes! Sorry, I should have inspected them more closely.

**Comment by jakirkham** [comment]
> It would be healthy to be less brittle to empty repos though :+1:

I suppose. Though it is good to know if I see this again.

**Comment by pelson** [comment]
The problem was:

```
Running command: ['python', '/home/travis/build/conda-forge/conda-forge.github.io/scripts/update_feedstocks_submodules.py', './feedstocks_repo']
Adding auditwheel to submodules.
Traceback (most recent call last):
  File "/home/travis/build/conda-forge/conda-forge.github.io/scripts/update_feedstocks_submodules.py", line 44, in <module>
    url=feedstock.clone_url)
  File "/home/travis/conda/tmp_envs/c08cdac88042ff143569/lib/python3.5/site-packages/git/repo/base.py", line 300, in create_submodule
    return Submodule.add(self, *args, **kwargs)
  File "/home/travis/conda/tmp_envs/c08cdac88042ff143569/lib/python3.5/site-packages/git/objects/submodule/base.py", line 415, in add
    sm.binsha = mrepo.head.commit.binsha
  File "/home/travis/conda/tmp_envs/c08cdac88042ff143569/lib/python3.5/site-packages/git/refs/symbolic.py", line 183, in _get_commit
    obj = self._get_object()
  File "/home/travis/conda/tmp_envs/c08cdac88042ff143569/lib/python3.5/site-packages/git/refs/symbolic.py", line 176, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
  File "/home/travis/conda/tmp_envs/c08cdac88042ff143569/lib/python3.5/site-packages/git/refs/symbolic.py", line 125, in dereference_recursive
    hexsha, ref_path = cls._get_ref_info(repo, ref_path)
  File "/home/travis/conda/tmp_envs/c08cdac88042ff143569/lib/python3.5/site-packages/git/refs/symbolic.py", line 157, in _get_ref_info
    raise ValueError("Reference at %r does not exist" % ref_path)
ValueError: Reference at 'refs/heads/master' does not exist
```

Same issue as https://github.com/gitpython-developers/GitPython/issues/55. I'm not sure whether to try fixing this or not...

**Comment by jakirkham** [comment]
Let's leave it for now. Maybe we could get a better error message. Though we are least familiar with the error one gets from this behavior.

**Comment by pelson** [comment]
Closing for now. We can re-open when needed.

**Comment by jakirkham** [comment]
Going to re-open as this is becoming more troublesome, but will add a PR with a fix.

**Comment by jakirkham** [comment]
See PR ( https://github.com/conda-forge/conda-forge.github.io/pull/66 ) for proposed fix.

**Comment by jakirkham** [comment]
Reopened as the warning did not fix it.

**Comment by jakirkham** [comment]
Turns out GitPython leaves a mess when failing to add a submodule. So, we use its interface to `git` to actually add the submodule. This seems to work correctly based on offline experiments. See this PR ( https://github.com/conda-forge/conda-forge.github.io/pull/68 )

**Comment by jakirkham** [comment]
It [works]( https://github.com/conda-forge/conda-forge.github.io/pull/68#issuecomment-203197485 ). :tada:

**Comment by ocefpaf** [comment]
Thanks @jakirkham!
