### ISSUE TITLE
Recipe build failing on OSX (after successful PR)

### ISSUE THREAD

**Issue by vidartf** [conda-forge/conda-forge.github.io#599]
For the pythreejs feedstock, I recently did a PR to fix a problem of missing files. Even without the missing files the previous build still succeeded. The PR just added a dependency on `nodejs`, and upped the build number (https://github.com/conda-forge/pythreejs-feedstock/pull/17). The CI for the PR succeeded, but the subsequent build from master fails for OSX: https://travis-ci.org/conda-forge/pythreejs-feedstock/builds/389298550 .

Details for posterity:
<details>
<summary>Python 2 trace</summary>
<pre>
copying build/lib/pythreejs/pythreejs.py -> /Users/travis/miniconda3/conda-bld/pythreejs_1528450377932/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python2.7/site-packages/pythreejs
error: [Errno 35] Resource temporarily unavailable
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
Traceback (most recent call last):
  File "/Users/travis/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 200, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 2177, in build_tree
    notest=notest,
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1417, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir, stats=build_stats)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/utils.py", line 310, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/utils.py", line 290, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/Users/travis/miniconda3/conda-bld/pythreejs_1528450377932/work/conda_build.sh']' returned non-zero exit status 1.
The command "conda build ./recipe -m ./.ci_support/${CONFIG}.yaml" exited with 1.
7.00s$ upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
Adding in variants from internal_defaults
Adding in variants from ./.ci_support/osx_python2.7.yaml
Attempting to finalize metadata for pythreejs
Solving environment: ...working... done
Solving environment: ...working... done
Processing pythreejs
[ERROR] File "/Users/travis/miniconda3/conda-bld/osx-64/pythreejs-1.1.0-py27_1.tar.bz2" does not exist
Traceback (most recent call last):
  File "/Users/travis/miniconda3/bin/upload_or_check_non_existence", line 131, in <module>
    main()
  File "/Users/travis/miniconda3/bin/upload_or_check_non_existence", line 121, in main
    upload(cli, fname, owner, channel)
  File "/Users/travis/miniconda3/bin/upload_or_check_non_existence", line 68, in upload
    env=os.environ)
  File "/Users/travis/miniconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['anaconda', '--quiet', '-t', '/var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/tmpavqh9v59/binstar.token', 'upload', '/Users/travis/miniconda3/conda-bld/osx-64/pythreejs-1.1.0-py27_1.tar.bz2', '--user=conda-forge', '--channel=main']' returned non-zero exit status 1.
The command "upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml" exited with 1.
</pre>
</details>

<details>
<summary>Python 3 trace</summary>
<pre>
copying build/lib/pythreejs/math/interpolants/__init__.py -> /Users/travis/miniconda3/conda-bld/pythreejs_1528450843407/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.5/site-packages/pythreejs/math/interpolants
copying build/lib/pythreejs/math/interpolants/CubicInterpolant_autogen.py -> /Users/travis/miniconda3/conda-bld/pythreejs_1528450843407/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.5/site-packages/pythreejs/math/interpolants
copying build/lib/pythreejs/math/interpolants/DiscreteInterpolant_autogen.py -> /Users/travis/miniconda3/conda-bld/pythreejs_1528450843407/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.5/site-packages/pythreejs/math/interpolants
error: [Errno 35] write could not complete without blocking
copying build/lib/pythreejs/math/interpolants/LinearInterpolant_autogen.py -> /Users/travis/miniconda3/conda-bld/pythreejs_1528450843407/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.5/site-packages/pythreejs/math/interpolants
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BlockingIOError: [Errno 35] write could not complete without blocking
Traceback (most recent call last):
  File "/Users/travis/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 200, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 2177, in build_tree
    notest=notest,
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1417, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir, stats=build_stats)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/utils.py", line 310, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/utils.py", line 290, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/Users/travis/miniconda3/conda-bld/pythreejs_1528450843407/work/conda_build.sh']' returned non-zero exit status 1.
The command "conda build ./recipe -m ./.ci_support/${CONFIG}.yaml" exited with 1.
7.00s$ upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
Adding in variants from internal_defaults
Adding in variants from ./.ci_support/osx_python3.5.yaml
Attempting to finalize metadata for pythreejs
Solving environment: ...working... done
Solving environment: ...working... done
Processing pythreejs
[ERROR] File "/Users/travis/miniconda3/conda-bld/osx-64/pythreejs-1.1.0-py35_1.tar.bz2" does not exist
Traceback (most recent call last):
  File "/Users/travis/miniconda3/bin/upload_or_check_non_existence", line 131, in <module>
    main()
  File "/Users/travis/miniconda3/bin/upload_or_check_non_existence", line 121, in main
    upload(cli, fname, owner, channel)
  File "/Users/travis/miniconda3/bin/upload_or_check_non_existence", line 68, in upload
    env=os.environ)
  File "/Users/travis/miniconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['anaconda', '--quiet', '-t', '/var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/tmpnfrm5mnu/binstar.token', 'upload', '/Users/travis/miniconda3/conda-bld/osx-64/pythreejs-1.1.0-py35_1.tar.bz2', '--user=conda-forge', '--channel=main']' returned non-zero exit status 1.
The command "upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml" exited with 1.
</pre>
</details>
<br/>
Does anybody know what could be causing this, or where the cause of the issue is (my code, travis, conda code)? I have no clue...

**Comment by vidartf** [comment]
Note: I've tried restarting the build several times, and the errors are reproducible over the last day.

**Comment by jakirkham** [comment]
Feedstock specific issue are best kept on feedstocks to keep things easy to follow. If you have questions about a PR, feel free to ping the feedstock maintainers, drop a note in gitter, and possibly ping core, basically in that order giving a little time between each. Thanks.

**Comment by vidartf** [comment]
Closing in favor of issue on feedstock with core ping (https://github.com/conda-forge/pythreejs-feedstock/issues/20).
