### ISSUE TITLE
Inconsistency in CI testing for noarch CRAN package

### ISSUE THREAD

**Issue by liiskolb** [conda-forge/conda-forge.github.io#864]
Issue: I have been trying to push my R package gprofiler2 to conda-forge and I'm seeing an unexpected behaviour in CI tests. Without actually changing anything in the meta.yaml file, checks fail in different platforms in separate commits. In one push, osx and linux fail, in other windows fails, and all other combinations as well. There seems to be something random happening. Do you have any idea what is going on?

The error message is always "conda.exceptions.UnsatisfiableError: The following specifications were found to be incompatible with each other:" 

https://github.com/conda-forge/staged-recipes/pull/9530

**Comment by scopatz** [comment]
Do you have the full error message?

**Comment by liiskolb** [comment]
The issue doesn't seem to be specific to the error message as the build seems to intermittently succeed or fail on different platforms.

But anyway, the full message is below. 

```
Found conflicts! Looking for incompatible packages.
This can take several minutes.

failed
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/environ.py", line 756, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda/plan.py", line 474, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
    should_retry_solve)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
    force_remove, should_retry_solve)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda/core/solve.py", line 281, in solve_final_state
    ssc = self._run_sat(ssc)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda/core/solve.py", line 805, in _run_sat
    should_retry_solve=ssc.should_retry_solve
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda/resolve.py", line 1277, in solve
    self.find_conflicts(specs, specs_to_add, history_specs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda/resolve.py", line 343, in find_conflicts
    raise UnsatisfiableError(bad_deps, strict=strict_channel_priority)
conda.exceptions.UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package r-rcpp conflicts for:
r-dplyr -> r-rcpp[version='>=0.11.6|>=0.12.0|>=0.12.15|>=0.12.19|>=0.12.6|>=0.12.7|>=1.0.0|>=1.0.1']
r-tidyr -> r-rcpp
r-plyr -> r-rcpp[version='>=0.11.0']
Package mro-base conflicts for:
r-jsonlite -> mro-base=3.5.0
Package r-plogr conflicts for:
r-dplyr -> r-plogr[version='>=0.1.10|>=0.2.0']
Package libtiff conflicts for:
r-base=3.5.1 -> libtiff[version='>=4.0.10,<5.0a0|>=4.0.9,<5.0a0']
Package r-base conflicts for:
r-crosstalk -> r-base[version='3.3.2.*|3.4.1.*|>=3.4.1,<3.4.2.0a0|>=3.4.2,<3.4.3a0|>=3.4.3,<3.4.4.0a0|>=3.5,<3.6.0a0|>=3.5.0,<3.5.1.0a0|>=3.5.1,<3.5.2.0a0|>=3.6,<3.7.0a0']
r-viridislite -> r-base[version='3.3.2.*|3.4.1.*|>=3.4.1,<3.4.2.0a0|>=3.4.2,<3.4.3a0|>=3.4.3,<3.4.4.0a0|>=3.5,<3.6.0a0|>=3.5.0,<3.5.1.0a0|>=3.5.1,<3.5.2.0a0|>=3.6,<3.7.0a0']
r-rcurl -> r-base[version='3.2.0.*|3.2.1.*|3.2.2.*|3.3.1.*|3.3.2.*|3.4.1.*|>=3.4.1,<3.4.2.0a0|>=3.4.2,<3.4.3a0|>=3.4.3,<3.4.4.0a0|>=3.5,<3.6.0a0|>=3.5.0,<3.5.1.0a0|>=3.5.1,<3.5.2.0a0|>=3.6,<3.7.0a0']
r-gridextra -> r-base[version='3.1.3.*|3.2.0.*|3.2.1.*|3.2.2.*|3.3.1.*|3.3.2.*|3.4.1.*|>=3.4.1,<3.4.2.0a0|>=3.4.2,<3.4.3a0|>=3.4.3,<3.4.4.0a0|>=3.5,<3.6.0a0|>=3.5.0,<3.5.1.0a0|>=3.5.1,<3.5.2.0a0|>=3.6,<3.7.0a0']
r-tidyr -> r-base[version='3.1.3.*|3.2.0.*|3.2.1.*|3.2.2.*|3.3.1.*|3.3.2.*|3.4.1.*|>=3.4.1,<3.4.2.0a0|>=3.4.2,<3.4.3a0|>=3.4.3,<3.4.4.0a0|>=3.5,<3.6.0a0|>=3.5.0,<3.5.1.0a0|>=3.5.1,<3.5.2.0a0|>=3.6,<3.7.0a0']
r-dplyr -> r-base[version='3.2.0.*|3.2.1.*|3.2.2.*|3.3.1.*|3.3.2.*|3.4.1.*|>=3.4.1,<3.4.2.0a0|>=3.4.2,<3.4.3a0|>=3.4.3,<3.4.4.0a0|>=3.5,<3.6.0a0|>=3.5.0,<3.5.1.0a0|>=3.5.1,<3.5.2.0a0|>=3.6,<3.7.0a0']
r-plotly -> r-base[version='3.3.2.*|3.4.1.*|>=3.4.1,<3.4.2.0a0|>=3.4.2,<3.4.3a0|>=3.4.3,<3.4.4.0a0|>=3.5,<3.6.0a0|>=3.5.0,<3.5.1.0a0|>=3.5.1,<3.5.2.0a0|>=3.6,<3.7.0a0']
r-ggplot2 -> r-base[version='3.2.0.*|3.2.1.*|3.2.2.*|3.3.1.*|3.3.2.*|3.4.1.*|>=3.4.1,<3.4.2.0a0|>=3.4.2,<3.4.3a0|>=3.4.3,<3.4.4.0a0|>=3.5,<3.6.0a0|>=3.5.0,<3.5.1.0a0|>=3.5.1,<3.5.2.0a0|>=3.6,<3.7.0a0']
r-jsonlite -> r-base[version='3.1.3.*|3.2.0.*|3.2.1.*|3.2.2.*|3.3.1.*|3.3.2.*|3.4.1.*|>=3.4.1,<3.4.2.0a0|>=3.4.2,<3.4.3a0|>=3.4.3,<3.4.4.0a0|>=3.5,<3.6.0a0|>=3.5.0,<3.5.1.0a0|>=3.5.1,<3.5.2.0a0|>=3.6,<3.7.0a0']
r-plyr -> r-base[version='3.2.0.*|3.2.1.*|3.2.2.*|3.3.1.*|3.3.2.*|3.4.1.*|>=3.4.1,<3.4.2.0a0|>=3.4.2,<3.4.3a0|>=3.4.3,<3.4.4.0a0|>=3.5,<3.6.0a0|>=3.5.0,<3.5.1.0a0|>=3.5.1,<3.5.2.0a0|>=3.6,<3.7.0a0']
Package krb5 conflicts for:
r-base=3.5.1 -> krb5[version='>=1.16.1,<1.17.0a0|>=1.16.2,<1.17.0a0|>=1.16.3,<1.17.0a0']
Package r-r6 conflicts for:
r-crosstalk -> r-r6
r-dplyr -> r-r6[version='>=2.2.2']
Package r-ggplot2 conflicts for:
r-crosstalk -> r-ggplot2
r-plotly -> r-ggplot2[version='>=2.2.1|>=3.0.0']
Package r-purrr conflicts for:
r-plotly -> r-purrr
r-tidyr -> r-purrr
Package make conflicts for:
r-base=3.5.1 -> make
Package libcxx conflicts for:
r-dplyr -> libcxx[version='>=4.0.1']
r-base=3.5.1 -> libcxx[version='>=4.0.1']
r-tidyr -> libcxx[version='>=4.0.1']
r-plyr -> libcxx[version='>=4.0.1']
Package _r-mutex conflicts for:
r-crosstalk -> _r-mutex=1[build=anacondar_1]
r-viridislite -> _r-mutex=1[build=anacondar_1]
r-tidyr -> _r-mutex=1[build=anacondar_1]
r-plyr -> _r-mutex=1[build=anacondar_1]
r-rcurl -> _r-mutex=1[build=anacondar_1]
r-plotly -> _r-mutex=1[build=anacondar_1]
r-ggplot2 -> _r-mutex=1[build=anacondar_1]
r-jsonlite -> _r-mutex=1[build='anacondar_1|mro_2']
r-gridextra -> _r-mutex=1[build=anacondar_1]
r-base=3.5.1 -> _r-mutex=1[build=anacondar_1]
r-dplyr -> _r-mutex=1[build=anacondar_1]
Package r-scales conflicts for:
r-ggplot2 -> r-scales[version='>=0.2.3|>=0.3.0|>=0.4.1|>=0.5.0']
r-plotly -> r-scales
Package r-rlang conflicts for:
r-ggplot2 -> r-rlang[version='>=0.2.1|>=0.3.0']
r-tidyr -> r-rlang
r-plotly -> r-rlang
r-dplyr -> r-rlang[version='>=0.1|>=0.1.2|>=0.2.0|>=0.3.0|>=0.3.1|>=0.4.0']
Package r-lazyeval conflicts for:
r-crosstalk -> r-lazyeval
r-dplyr -> r-lazyeval[version='>=0.1.10']
r-ggplot2 -> r-lazyeval
r-plotly -> r-lazyeval[version='>=0.2.0']
r-tidyr -> r-lazyeval
Package tktable conflicts for:
r-base=3.5.1 -> tktable
Package zlib conflicts for:
r-base=3.5.1 -> zlib[version='>=1.2.11,<1.3.0a0']
Package r-mgcv conflicts for:
r-ggplot2 -> r-mgcv
Package r-magrittr conflicts for:
r-tidyr -> r-magrittr
r-plotly -> r-magrittr
r-dplyr -> r-magrittr[version='>=1.5']
Package libgcc conflicts for:
r-dplyr -> libgcc
r-rcurl -> libgcc
r-plyr -> libgcc
r-tidyr -> libgcc
r-jsonlite -> libgcc
Package libcurl conflicts for:
r-base=3.5.1 -> libcurl[version='>=7.61.0,<8.0a0|>=7.62.0,<8.0a0|>=7.64.1,<8.0a0']
r-rcurl -> libcurl[version='>=7.58.0,<8.0a0|>=7.60.0,<8.0a0|>=7.61.0,<8.0a0|>=7.61.1,<8.0a0|>=7.62.0,<8.0a0|>=7.64.0,<8.0a0|>=7.64.1,<8.0a0']
Package r-digest conflicts for:
r-plotly -> r-digest
r-ggplot2 -> r-digest
Package r-glue conflicts for:
r-dplyr -> r-glue[version='>=1.1.1|>=1.3.0']
r-tidyr -> r-glue
Package r-crosstalk conflicts for:
r-plotly -> r-crosstalk
Package r-gtable conflicts for:
r-gridextra -> r-gtable
r-ggplot2 -> r-gtable[version='>=0.1.1']
Package pango conflicts for:
r-base=3.5.1 -> pango[version='>=1.40.14,<1.41.0a0|>=1.42.4,<1.43.0a0|>=1.42.4,<2.0a0']
Package r-tidyselect conflicts for:
r-dplyr -> r-tidyselect[version='>=0.2.3|>=0.2.5']
r-tidyr -> r-tidyselect[version='>=0.2.5']
Package r-tibble conflicts for:
r-dplyr -> r-tibble[version='>=1.3.1|>=1.4.2|>=2.0.0']
r-tidyr -> r-tibble
r-ggplot2 -> r-tibble
r-plotly -> r-tibble
Package r-stringi conflicts for:
r-tidyr -> r-stringi
Package jpeg conflicts for:
r-base=3.5.1 -> jpeg[version='>=9b,<10a|>=9c,<10a']
Package r-rcolorbrewer conflicts for:
r-plotly -> r-rcolorbrewer
Package r-bindrcpp conflicts for:
r-dplyr -> r-bindrcpp[version='>=0.2|>=0.2.0.9000']
Package r-reshape2 conflicts for:
r-ggplot2 -> r-reshape2
r-tidyr -> r-reshape2
Package libgfortran conflicts for:
r-base=3.5.1 -> libgfortran[version='>=3.0,<4.0.0.a0|>=3.0.1|>=3.0.1,<4.0.0.a0|>=4.0.0,<5.0.0.a0']
Package r-pkgconfig conflicts for:
r-dplyr -> r-pkgconfig[version='>=2.0.1']
Package ncurses conflicts for:
r-base=3.5.1 -> ncurses[version='>=6.1,<7.0a0']
Package libiconv conflicts for:
r-base=3.5.1 -> libiconv[version='>=1.15,<1.16.0a0|>=1.15,<2.0a0']
Package r-viridislite conflicts for:
r-ggplot2 -> r-viridislite
r-plotly -> r-viridislite
Package r-withr conflicts for:
r-ggplot2 -> r-withr[version='>=2.0.0']
Package r-plyr conflicts for:
r-ggplot2 -> r-plyr[version='>=1.7.1']
Package r-htmlwidgets conflicts for:
r-plotly -> r-htmlwidgets[version='>=0.9|>=1.2|>=1.3']
Package clang_osx-64 conflicts for:
r-base=3.5.1 -> clang_osx-64=4
Package r-jsonlite conflicts for:
r-crosstalk -> r-jsonlite
r-plotly -> r-jsonlite[version='>=1.6']
Package r-htmltools conflicts for:
r-plotly -> r-htmltools[version='>=0.3.6']
r-crosstalk -> r-htmltools[version='>=0.3.5']
Package bzip2 conflicts for:
r-base=3.5.1 -> bzip2[version='>=1.0.6,<2.0a0|>=1.0.8,<2.0a0']
Package pcre conflicts for:
r-base=3.5.1 -> pcre[version='>=8.41,<9.0a0|>=8.42,<9.0a0']
Package r-dbi conflicts for:
r-dplyr -> r-dbi[version='>=0.3|>=0.4.1']
Package gsl conflicts for:
r-base=3.5.1 -> gsl[version='>=2.2.1,<2.3.0a0|>=2.4,<2.5.0a0|>=2.5,<2.6.0a0']
Package libpng conflicts for:
r-base=3.5.1 -> libpng[version='>=1.6.34,<1.7.0a0|>=1.6.35,<1.7.0a0|>=1.6.37,<1.7.0a0']
Package libxml2 conflicts for:
r-base=3.5.1 -> libxml2[version='>=2.9.8,<2.10.0a0|>=2.9.9,<2.10.0a0']
Package r-data.table conflicts for:
r-plotly -> r-data.table
Package r-hexbin conflicts for:
r-plotly -> r-hexbin
Package r-bitops conflicts for:
r-rcurl -> r-bitops
Package r-dplyr conflicts for:
r-plotly -> r-dplyr
r-tidyr -> r-dplyr[version='>=0.2|>=0.4|>=0.7.0']
Package tk conflicts for:
r-base=3.5.1 -> tk[version='>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
Package curl conflicts for:
r-rcurl -> curl[version='>=7.59.0,<8.0a0']
r-base=3.5.1 -> curl
Package r-httr conflicts for:
r-plotly -> r-httr
Package r-mass conflicts for:
r-ggplot2 -> r-mass
Package icu conflicts for:
r-base=3.5.1 -> icu[version='>=58.2,<59.0a0|>=64.2,<65.0a0']
Package r-proto conflicts for:
r-ggplot2 -> r-proto
Package r-tidyr conflicts for:
r-plotly -> r-tidyr
Package llvm-openmp conflicts for:
r-base=3.5.1 -> llvm-openmp[version='>=4.0.1|>=8.0.0|>=8.0.1']
Package r-base64enc conflicts for:
r-plotly -> r-base64enc
Package readline conflicts for:
r-base=3.5.1 -> readline[version='>=7.0,<8.0a0|>=8.0,<9.0a0']
Package clangxx_osx-64 conflicts for:
r-base=3.5.1 -> clangxx_osx-64=4
Package r-shiny conflicts for:
r-crosstalk -> r-shiny[version='>=0.11']
Package bwidget conflicts for:
r-base=3.5.1 -> bwidget
Package xz conflicts for:
r-base=3.5.1 -> xz[version='>=5.2.4,<5.3.0a0|>=5.2.4,<6.0a0']
Package r-assertthat conflicts for:
r-dplyr -> r-assertthat[version='>=0.2.0']
Package gfortran_osx-64 conflicts for:
r-base=3.5.1 -> gfortran_osx-64[version='4.*|7.*']
Package r-promises conflicts for:
r-plotly -> r-promises
Package cairo conflicts for:
r-base=3.5.1 -> cairo[version='>=1.14.12,<1.15.0a0|>=1.14.12,<2.0a0|>=1.16.0,<1.17.0a0']
Package r-bh conflicts for:
r-dplyr -> r-bh[version='>=1.58.0_1']
Package libssh2 conflicts for:
r-base=3.5.1 -> libssh2[version='>=1.8.0,<1.9.0a0|>=1.8.0,<2.0a0|>=1.8.2,<1.9.0a0']
Package freetype conflicts for:
r-base=3.5.1 -> freetype[version='>=2.9.1,<3.0a0']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".ci_support/build_all.py", line 131, in <module>
    build_all(args.recipes_dir, args.arch)
  File ".ci_support/build_all.py", line 68, in build_all
    build_folders(recipes_dir, new_comp_folders, arch, channel_urls)
  File ".ci_support/build_all.py", line 121, in build_folders
    conda_build.api.build([recipe], config=get_config(arch, channel_urls))
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/build.py", line 2343, in build_tree
    notest=notest,
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/build.py", line 1334, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/render.py", line 746, in expand_outputs
    for (output_dict, m) in _m.copy().get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/metadata.py", line 2047, in get_output_metadata_set
    bypass_env_check=bypass_env_check)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/metadata.py", line 721, in finalize_outputs_pass
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/render.py", line 527, in finalize_metadata
    exclude_pattern)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/render.py", line 412, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/render.py", line 378, in _read_upstream_pin_files
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/render.py", line 154, in get_env_dependencies
    channel_urls=tuple(m.config.channel_urls))
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/environ.py", line 758, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/exceptions.py", line 78, in __init__
    " {}".format(str(conda_exception)))
RuntimeError: failed to parse packages from exception: The following specifications were found to be incompatible with each other:



Package r-rcpp conflicts for:
r-dplyr -> r-rcpp[version='>=0.11.6|>=0.12.0|>=0.12.15|>=0.12.19|>=0.12.6|>=0.12.7|>=1.0.0|>=1.0.1']
r-tidyr -> r-rcpp
r-plyr -> r-rcpp[version='>=0.11.0']
Package mro-base conflicts for:
r-jsonlite -> mro-base=3.5.0
Package r-plogr conflicts for:
r-dplyr -> r-plogr[version='>=0.1.10|>=0.2.0']
Package libtiff conflicts for:
r-base=3.5.1 -> libtiff[version='>=4.0.10,<5.0a0|>=4.0.9,<5.0a0']
Package r-base conflicts for:
r-crosstalk -> r-base[version='3.3.2.*|3.4.1.*|>=3.4.1,<3.4.2.0a0|>=3.4.2,<3.4.3a0|>=3.4.3,<3.4.4.0a0|>=3.5,<3.6.0a0|>=3.5.0,<3.5.1.0a0|>=3.5.1,<3.5.2.0a0|>=3.6,<3.7.0a0']
r-viridislite -> r-base[version='3.3.2.*|3.4.1.*|>=3.4.1,<3.4.2.0a0|>=3.4.2,<3.4.3a0|>=3.4.3,<3.4.4.0a0|>=3.5,<3.6.0a0|>=3.5.0,<3.5.1.0a0|>=3.5.1,<3.5.2.0a0|>=3.6,<3.7.0a0']
r-rcurl -> r-base[version='3.2.0.*|3.2.1.*|3.2.2.*|3.3.1.*|3.3.2.*|3.4.1.*|>=3.4.1,<3.4.2.0a0|>=3.4.2,<3.4.3a0|>=3.4.3,<3.4.4.0a0|>=3.5,<3.6.0a0|>=3.5.0,<3.5.1.0a0|>=3.5.1,<3.5.2.0a0|>=3.6,<3.7.0a0']
r-gridextra -> r-base[version='3.1.3.*|3.2.0.*|3.2.1.*|3.2.2.*|3.3.1.*|3.3.2.*|3.4.1.*|>=3.4.1,<3.4.2.0a0|>=3.4.2,<3.4.3a0|>=3.4.3,<3.4.4.0a0|>=3.5,<3.6.0a0|>=3.5.0,<3.5.1.0a0|>=3.5.1,<3.5.2.0a0|>=3.6,<3.7.0a0']
r-tidyr -> r-base[version='3.1.3.*|3.2.0.*|3.2.1.*|3.2.2.*|3.3.1.*|3.3.2.*|3.4.1.*|>=3.4.1,<3.4.2.0a0|>=3.4.2,<3.4.3a0|>=3.4.3,<3.4.4.0a0|>=3.5,<3.6.0a0|>=3.5.0,<3.5.1.0a0|>=3.5.1,<3.5.2.0a0|>=3.6,<3.7.0a0']
r-dplyr -> r-base[version='3.2.0.*|3.2.1.*|3.2.2.*|3.3.1.*|3.3.2.*|3.4.1.*|>=3.4.1,<3.4.2.0a0|>=3.4.2,<3.4.3a0|>=3.4.3,<3.4.4.0a0|>=3.5,<3.6.0a0|>=3.5.0,<3.5.1.0a0|>=3.5.1,<3.5.2.0a0|>=3.6,<3.7.0a0']
r-plotly -> r-base[version='3.3.2.*|3.4.1.*|>=3.4.1,<3.4.2.0a0|>=3.4.2,<3.4.3a0|>=3.4.3,<3.4.4.0a0|>=3.5,<3.6.0a0|>=3.5.0,<3.5.1.0a0|>=3.5.1,<3.5.2.0a0|>=3.6,<3.7.0a0']
r-ggplot2 -> r-base[version='3.2.0.*|3.2.1.*|3.2.2.*|3.3.1.*|3.3.2.*|3.4.1.*|>=3.4.1,<3.4.2.0a0|>=3.4.2,<3.4.3a0|>=3.4.3,<3.4.4.0a0|>=3.5,<3.6.0a0|>=3.5.0,<3.5.1.0a0|>=3.5.1,<3.5.2.0a0|>=3.6,<3.7.0a0']
r-jsonlite -> r-base[version='3.1.3.*|3.2.0.*|3.2.1.*|3.2.2.*|3.3.1.*|3.3.2.*|3.4.1.*|>=3.4.1,<3.4.2.0a0|>=3.4.2,<3.4.3a0|>=3.4.3,<3.4.4.0a0|>=3.5,<3.6.0a0|>=3.5.0,<3.5.1.0a0|>=3.5.1,<3.5.2.0a0|>=3.6,<3.7.0a0']
r-plyr -> r-base[version='3.2.0.*|3.2.1.*|3.2.2.*|3.3.1.*|3.3.2.*|3.4.1.*|>=3.4.1,<3.4.2.0a0|>=3.4.2,<3.4.3a0|>=3.4.3,<3.4.4.0a0|>=3.5,<3.6.0a0|>=3.5.0,<3.5.1.0a0|>=3.5.1,<3.5.2.0a0|>=3.6,<3.7.0a0']
Package krb5 conflicts for:
r-base=3.5.1 -> krb5[version='>=1.16.1,<1.17.0a0|>=1.16.2,<1.17.0a0|>=1.16.3,<1.17.0a0']
Package r-r6 conflicts for:
r-crosstalk -> r-r6
r-dplyr -> r-r6[version='>=2.2.2']
Package r-ggplot2 conflicts for:
r-crosstalk -> r-ggplot2
r-plotly -> r-ggplot2[version='>=2.2.1|>=3.0.0']
Package r-purrr conflicts for:
r-plotly -> r-purrr
r-tidyr -> r-purrr
Package make conflicts for:
r-base=3.5.1 -> make
Package libcxx conflicts for:
r-dplyr -> libcxx[version='>=4.0.1']
r-base=3.5.1 -> libcxx[version='>=4.0.1']
r-tidyr -> libcxx[version='>=4.0.1']
r-plyr -> libcxx[version='>=4.0.1']
Package _r-mutex conflicts for:
r-crosstalk -> _r-mutex=1[build=anacondar_1]
r-viridislite -> _r-mutex=1[build=anacondar_1]
r-tidyr -> _r-mutex=1[build=anacondar_1]
r-plyr -> _r-mutex=1[build=anacondar_1]
r-rcurl -> _r-mutex=1[build=anacondar_1]
r-plotly -> _r-mutex=1[build=anacondar_1]
r-ggplot2 -> _r-mutex=1[build=anacondar_1]
r-jsonlite -> _r-mutex=1[build='anacondar_1|mro_2']
r-gridextra -> _r-mutex=1[build=anacondar_1]
r-base=3.5.1 -> _r-mutex=1[build=anacondar_1]
r-dplyr -> _r-mutex=1[build=anacondar_1]
Package r-scales conflicts for:
r-ggplot2 -> r-scales[version='>=0.2.3|>=0.3.0|>=0.4.1|>=0.5.0']
r-plotly -> r-scales
Package r-rlang conflicts for:
r-ggplot2 -> r-rlang[version='>=0.2.1|>=0.3.0']
r-tidyr -> r-rlang
r-plotly -> r-rlang
r-dplyr -> r-rlang[version='>=0.1|>=0.1.2|>=0.2.0|>=0.3.0|>=0.3.1|>=0.4.0']
Package r-lazyeval conflicts for:
r-crosstalk -> r-lazyeval
r-dplyr -> r-lazyeval[version='>=0.1.10']
r-ggplot2 -> r-lazyeval
r-plotly -> r-lazyeval[version='>=0.2.0']
r-tidyr -> r-lazyeval
Package tktable conflicts for:
r-base=3.5.1 -> tktable
Package zlib conflicts for:
r-base=3.5.1 -> zlib[version='>=1.2.11,<1.3.0a0']
Package r-mgcv conflicts for:
r-ggplot2 -> r-mgcv
Package r-magrittr conflicts for:
r-tidyr -> r-magrittr
r-plotly -> r-magrittr
r-dplyr -> r-magrittr[version='>=1.5']
Package libgcc conflicts for:
r-dplyr -> libgcc
r-rcurl -> libgcc
r-plyr -> libgcc
r-tidyr -> libgcc
r-jsonlite -> libgcc
Package libcurl conflicts for:
r-base=3.5.1 -> libcurl[version='>=7.61.0,<8.0a0|>=7.62.0,<8.0a0|>=7.64.1,<8.0a0']
r-rcurl -> libcurl[version='>=7.58.0,<8.0a0|>=7.60.0,<8.0a0|>=7.61.0,<8.0a0|>=7.61.1,<8.0a0|>=7.62.0,<8.0a0|>=7.64.0,<8.0a0|>=7.64.1,<8.0a0']
Package r-digest conflicts for:
r-plotly -> r-digest
r-ggplot2 -> r-digest
Package r-glue conflicts for:
r-dplyr -> r-glue[version='>=1.1.1|>=1.3.0']
r-tidyr -> r-glue
Package r-crosstalk conflicts for:
r-plotly -> r-crosstalk
Package r-gtable conflicts for:
r-gridextra -> r-gtable
r-ggplot2 -> r-gtable[version='>=0.1.1']
Package pango conflicts for:
r-base=3.5.1 -> pango[version='>=1.40.14,<1.41.0a0|>=1.42.4,<1.43.0a0|>=1.42.4,<2.0a0']
Package r-tidyselect conflicts for:
r-dplyr -> r-tidyselect[version='>=0.2.3|>=0.2.5']
r-tidyr -> r-tidyselect[version='>=0.2.5']
Package r-tibble conflicts for:
r-dplyr -> r-tibble[version='>=1.3.1|>=1.4.2|>=2.0.0']
r-tidyr -> r-tibble
r-ggplot2 -> r-tibble
r-plotly -> r-tibble
Package r-stringi conflicts for:
r-tidyr -> r-stringi
Package jpeg conflicts for:
r-base=3.5.1 -> jpeg[version='>=9b,<10a|>=9c,<10a']
Package r-rcolorbrewer conflicts for:
r-plotly -> r-rcolorbrewer
Package r-bindrcpp conflicts for:
r-dplyr -> r-bindrcpp[version='>=0.2|>=0.2.0.9000']
Package r-reshape2 conflicts for:
r-ggplot2 -> r-reshape2
r-tidyr -> r-reshape2
Package libgfortran conflicts for:
r-base=3.5.1 -> libgfortran[version='>=3.0,<4.0.0.a0|>=3.0.1|>=3.0.1,<4.0.0.a0|>=4.0.0,<5.0.0.a0']
Package r-pkgconfig conflicts for:
r-dplyr -> r-pkgconfig[version='>=2.0.1']
Package ncurses conflicts for:
r-base=3.5.1 -> ncurses[version='>=6.1,<7.0a0']
Package libiconv conflicts for:
r-base=3.5.1 -> libiconv[version='>=1.15,<1.16.0a0|>=1.15,<2.0a0']
Package r-viridislite conflicts for:
r-ggplot2 -> r-viridislite
r-plotly -> r-viridislite
Package r-withr conflicts for:
r-ggplot2 -> r-withr[version='>=2.0.0']
Package r-plyr conflicts for:
r-ggplot2 -> r-plyr[version='>=1.7.1']
Package r-htmlwidgets conflicts for:
r-plotly -> r-htmlwidgets[version='>=0.9|>=1.2|>=1.3']
Package clang_osx-64 conflicts for:
r-base=3.5.1 -> clang_osx-64=4
Package r-jsonlite conflicts for:
r-crosstalk -> r-jsonlite
r-plotly -> r-jsonlite[version='>=1.6']
Package r-htmltools conflicts for:
r-plotly -> r-htmltools[version='>=0.3.6']
r-crosstalk -> r-htmltools[version='>=0.3.5']
Package bzip2 conflicts for:
r-base=3.5.1 -> bzip2[version='>=1.0.6,<2.0a0|>=1.0.8,<2.0a0']
Package pcre conflicts for:
r-base=3.5.1 -> pcre[version='>=8.41,<9.0a0|>=8.42,<9.0a0']
Package r-dbi conflicts for:
r-dplyr -> r-dbi[version='>=0.3|>=0.4.1']
Package gsl conflicts for:
r-base=3.5.1 -> gsl[version='>=2.2.1,<2.3.0a0|>=2.4,<2.5.0a0|>=2.5,<2.6.0a0']
Package libpng conflicts for:
r-base=3.5.1 -> libpng[version='>=1.6.34,<1.7.0a0|>=1.6.35,<1.7.0a0|>=1.6.37,<1.7.0a0']
Package libxml2 conflicts for:
r-base=3.5.1 -> libxml2[version='>=2.9.8,<2.10.0a0|>=2.9.9,<2.10.0a0']
Package r-data.table conflicts for:
r-plotly -> r-data.table
Package r-hexbin conflicts for:
r-plotly -> r-hexbin
Package r-bitops conflicts for:
r-rcurl -> r-bitops
Package r-dplyr conflicts for:
r-plotly -> r-dplyr
r-tidyr -> r-dplyr[version='>=0.2|>=0.4|>=0.7.0']
Package tk conflicts for:
r-base=3.5.1 -> tk[version='>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
Package curl conflicts for:
r-rcurl -> curl[version='>=7.59.0,<8.0a0']
r-base=3.5.1 -> curl
Package r-httr conflicts for:
r-plotly -> r-httr
Package r-mass conflicts for:
r-ggplot2 -> r-mass
Package icu conflicts for:
r-base=3.5.1 -> icu[version='>=58.2,<59.0a0|>=64.2,<65.0a0']
Package r-proto conflicts for:
r-ggplot2 -> r-proto
Package r-tidyr conflicts for:
r-plotly -> r-tidyr
Package llvm-openmp conflicts for:
r-base=3.5.1 -> llvm-openmp[version='>=4.0.1|>=8.0.0|>=8.0.1']
Package r-base64enc conflicts for:
r-plotly -> r-base64enc
Package readline conflicts for:
r-base=3.5.1 -> readline[version='>=7.0,<8.0a0|>=8.0,<9.0a0']
Package clangxx_osx-64 conflicts for:
r-base=3.5.1 -> clangxx_osx-64=4
Package r-shiny conflicts for:
r-crosstalk -> r-shiny[version='>=0.11']
Package bwidget conflicts for:
r-base=3.5.1 -> bwidget
Package xz conflicts for:
r-base=3.5.1 -> xz[version='>=5.2.4,<5.3.0a0|>=5.2.4,<6.0a0']
Package r-assertthat conflicts for:
r-dplyr -> r-assertthat[version='>=0.2.0']
Package gfortran_osx-64 conflicts for:
r-base=3.5.1 -> gfortran_osx-64[version='4.*|7.*']
Package r-promises conflicts for:
r-plotly -> r-promises
Package cairo conflicts for:
r-base=3.5.1 -> cairo[version='>=1.14.12,<1.15.0a0|>=1.14.12,<2.0a0|>=1.16.0,<1.17.0a0']
Package r-bh conflicts for:
r-dplyr -> r-bh[version='>=1.58.0_1']
Package libssh2 conflicts for:
r-base=3.5.1 -> libssh2[version='>=1.8.0,<1.9.0a0|>=1.8.0,<2.0a0|>=1.8.2,<1.9.0a0']
Package freetype conflicts for:
r-base=3.5.1 -> freetype[version='>=2.9.1,<3.0a0']
##[error]Bash exited with code '1'.
```
