### ISSUE TITLE
jupyter notebook and qtconsole not working for python 3.5

### ISSUE THREAD

**Issue by cbeebe44** [conda-forge/conda-forge.github.io#956]
# Issue:  Cannot get jupyter notebook or qtconsole to work on python 3.5
jupyter notebook launches in browser but cannot start a kernel.
I get the following error with <code> jupyter notebook</code>:

<details>

```
Traceback (most recent call last):
  File "C:\Users\Aka\Miniconda3\envs\test01\lib\site-packages\notebook\base\handlers.py", line 503, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "C:\Users\Aka\Miniconda3\envs\test01\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\Aka\Miniconda3\envs\test01\lib\asyncio\futures.py", line 294, in result
    raise self._exception
  File "C:\Users\Aka\Miniconda3\envs\test01\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\Aka\Miniconda3\envs\test01\lib\site-packages\notebook\services\sessions\handlers.py", line 75, in post
    type=mtype))
  File "C:\Users\Aka\Miniconda3\envs\test01\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\Aka\Miniconda3\envs\test01\lib\asyncio\futures.py", line 294, in result
    raise self._exception
  File "C:\Users\Aka\Miniconda3\envs\test01\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\Aka\Miniconda3\envs\test01\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\Aka\Miniconda3\envs\test01\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\Aka\Miniconda3\envs\test01\lib\asyncio\futures.py", line 294, in result
    raise self._exception
  File "C:\Users\Aka\Miniconda3\envs\test01\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\Aka\Miniconda3\envs\test01\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\Aka\Miniconda3\envs\test01\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\Aka\Miniconda3\envs\test01\lib\asyncio\futures.py", line 294, in result
    raise self._exception
  File "C:\Users\Aka\Miniconda3\envs\test01\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\Users\Aka\Miniconda3\envs\test01\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 87, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\Aka\Miniconda3\envs\test01\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\Aka\Miniconda3\envs\test01\lib\site-packages\jupyter_client\manager.py", line 259, in start_kernel
    **kw)
  File "C:\Users\Aka\Miniconda3\envs\test01\lib\site-packages\jupyter_client\manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Users\Aka\Miniconda3\envs\test01\lib\site-packages\jupyter_client\launcher.py", line 138, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Users\Aka\Miniconda3\envs\test01\lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Aka\Miniconda3\envs\test01\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
</details>

This is the error I get when trying <code> jupyter qtconsole </code>:
<details>

```

Traceback (most recent call last):
  File "C:\Users\Aka\Miniconda3\envs\test01\Scripts\jupyter-qtconsole-script.py", line 5, in <module>
    from qtconsole.qtconsoleapp import main
  File "C:\Users\Aka\Miniconda3\envs\test01\lib\site-packages\qtconsole\qtconsoleapp.py", line 60, in <module>
    from qtconsole.qt import QtCore, QtGui
  File "C:\Users\Aka\Miniconda3\envs\test01\lib\site-packages\qtconsole\qt.py", line 23, in <module>
    QtCore, QtGui, QtSvg, QT_API = load_qt(api_opts)
  File "C:\Users\Aka\Miniconda3\envs\test01\lib\site-packages\qtconsole\qt_loaders.py", line 366, in load_qt
    result = loaders[api]()
  File "C:\Users\Aka\Miniconda3\envs\test01\lib\site-packages\qtconsole\qt_loaders.py", line 271, in import_pyqt5
    from PyQt5 import QtCore, QtSvg, QtWidgets, QtGui, QtPrintSupport
ImportError: DLL load failed: The specified module could not be found.
```
</details>

Things that I have tried:

- reinstall miniconda and upgrade conda
- install packages from conda-forge channel
- install pywin32
- run pywin32_postinstall.py script
- spend hours on the web looking for possible solutions

### Please help

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at C:\Users\Aka\Miniconda3\envs\test01:
#
# Name                    Version                   Build  Channel
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.0                      py_0    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2018.8.24             py35_1001    conda-forge
colorama                  0.4.3                      py_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
entrypoints               0.2.3                    py35_2    conda-forge
icu                       64.2                 he025d50_1    conda-forge
ipykernel                 5.1.0              pyh24bf2e0_0    conda-forge
ipython                   7.0.1            py35h39e3cac_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
jedi                      0.12.1                   py35_0    conda-forge
jinja2                    2.10.3                     py_0    conda-forge
jpeg                      9c                hfa6e2cd_1001    conda-forge
jsonschema                2.6.0                    py35_2    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            5.3.3                      py_0    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.5.0                      py_0    conda-forge
libpng                    1.6.37               h7602738_0    conda-forge
markupsafe                1.0              py35hfa6e2cd_1    conda-forge
mistune                   0.8.3            py35hfa6e2cd_2    conda-forge
nbconvert                 5.6.0                      py_0    conda-forge
nbformat                  5.0.3                      py_0    conda-forge
notebook                  4.4.1                    py35_0    conda-forge
openssl                   1.1.1d               hfa6e2cd_0    conda-forge
pandoc                    2.9.1.1                       0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.5.2                      py_0    conda-forge
pickleshare               0.7.5                    py35_0    conda-forge
pip                       18.0                  py35_1001    conda-forge
prompt_toolkit            2.0.10                     py_0    conda-forge
pygments                  2.5.2                      py_0    conda-forge
pyqt                      5.9.2            py35h6538335_2  
python                    3.5.5                he025d50_2    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
pywin32                   223             py35hfa6e2cd_1000    conda-forge
pyzmq                     17.0.0                   py35_3    conda-forge
qt                        5.9.7                h506e8af_3    conda-forge
qtconsole                 4.6.0                      py_0    conda-forge
setuptools                40.4.3                   py35_0    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
sip                       4.19.8          py35h6538335_1000    conda-forge
six                       1.11.0                   py35_1    conda-forge
sqlite                    3.30.1               hfa6e2cd_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tornado                   5.1.1            py35hfa6e2cd_0    conda-forge
traitlets                 4.3.2                    py35_0    conda-forge
vc                        14.1                 h0510ff6_4  
vs2015_runtime            14.16.27012          hf0eaf9b_1  
wcwidth                   0.1.8                      py_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.32.0                py35_1000    conda-forge
widgetsnbextension        3.4.2                    py35_0    conda-forge
win_unicode_console       0.5                      py35_0    conda-forge
wincertstore              0.2                   py35_1002    conda-forge
zlib                      1.2.11            h2fa13f4_1006    conda-forge


```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : test01
    active env location : C:\Users\Aka\Miniconda3\envs\test01
            shell level : 2
       user config file : C:\Users\Aka\.condarc
 populated config files : C:\Users\Aka\.condarc
          conda version : 4.8.1
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages : __cuda=10.1
       base environment : C:\Users\Aka\Miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/menpo/win-64
                          https://conda.anaconda.org/menpo/noarch
                          https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Aka\Miniconda3\pkgs
                          C:\Users\Aka\.conda\pkgs
                          C:\Users\Aka\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Aka\Miniconda3\envs
                          C:\Users\Aka\.conda\envs
                          C:\Users\Aka\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.1 requests/2.22.0 CPython/3.7.4 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False



```
</details>

**Comment by jakirkham** [comment]
Sorry you are having trouble. Unfortunately we dropped support for Python 3.5 sometime back. Would try to update to Python 3.6 at a minimum if possible.

**Comment by cbeebe44** [comment]
wow that sucks.
anyway i got it working with pip not conda-forge.
thanks
